# Generated by Django 4.1.6 on 2023-05-07 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookswaplibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(blank=True, choices=[('h', 'Home'), ('b', 'Business'), ('l', 'Library')], default='e', help_text='Location Type', max_length=2)),
                ('street_no', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=9)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('external_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=500)),
                ('image', models.ImageField(null=True, upload_to='images/bookcovers')),
                ('author', models.ManyToManyField(to='bookswaplibrary.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookImageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/bookinstanceimages/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('e', 'Excellent'), ('g', 'Good'), ('f', 'Fair'), ('m', 'Missing Pages')], max_length=1)),
                ('status', models.CharField(choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookswaplibrary.book')),
                ('images', models.ManyToManyField(to='bookswaplibrary.bookimageinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=200)),
                ('external_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookswaplibrary.address')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('date_exchanged', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('r', 'Return'), ('n', 'Return Not Required'), ('e', 'Exchanged'), ('s', 'Sold')], default='r', help_text='Return Requirements', max_length=1)),
                ('books', models.ManyToManyField(to='bookswaplibrary.bookinstance')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='bookswaplibrary.member')),
                ('exchange_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookswaplibrary.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='bookswaplibrary.member')),
            ],
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookswaplibrary.member'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='bookswaplibrary.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='bookswaplibrary.publisher'),
        ),
    ]
