# Generated by Django 4.1.6 on 2023-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswaplibrary', '0003_alter_bookimageinstance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='images',
            field=models.ManyToManyField(related_name='book_images', to='bookswaplibrary.bookimageinstance'),
        ),
    ]
