# Generated by Django 4.1.6 on 2023-05-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookswaplibrary', '0004_alter_bookinstance_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookswaplibrary.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/bookimages')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='images',
        ),
        migrations.DeleteModel(
            name='BookImageInstance',
        ),
        migrations.AddField(
            model_name='bookinstanceimage',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookswaplibrary.bookinstance'),
        ),
        migrations.AddField(
            model_name='bookinstanceimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookswaplibrary.image'),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookswaplibrary.image'),
        ),
    ]
