# Generated by Django 4.1.6 on 2023-05-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswaplibrary', '0007_alter_bookimage_image_alter_bookinstanceimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimage',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ManyToManyField(to='bookswaplibrary.bookimage'),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
