# Generated by Django 4.1.6 on 2023-05-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswaplibrary', '0010_remove_bookinstanceimage_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimage',
            name='description',
        ),
        migrations.AddField(
            model_name='bookinstanceimage',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
