# Generated by Django 4.1.6 on 2023-06-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookswaplibrary', '0011_remove_bookimage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='available',
        ),
    ]
