# Generated by Django 4.1.6 on 2023-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswaplibrary', '0015_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location_type',
            field=models.CharField(blank=True, choices=[('h', 'Home'), ('b', 'Business'), ('l', 'Library')], default='e', max_length=2),
        ),
    ]
