# Generated by Django 4.1.6 on 2023-06-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookswaplibrary', '0016_alter_address_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='status',
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField()),
                ('accept', models.BooleanField()),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookswaplibrary.bookinstance')),
            ],
        ),
    ]
